//user reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
//UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
//Data reducer types
// Publicaciones
export const SET_PUBLICACIONES = 'SET_PUBLICACIONES';
export const SET_PUBLICACION = 'SET_PUBLICACION';
export const LIKE_PUBLICACION = 'LIKE_PUBLICACION';
export const UNLIKE_PUBLICACION = 'UNLIKE_PUBLICACION';
export const DONTLIKE_PUBLICACION = 'DONTLIKE_PUBLICACION';
export const UNDODONTLIKE_PUBLICACION = "UNDODONTLIKE_PUBLICACION";
export const DELETE_PUBLICACION = 'DELETE_PUBLICACION';
export const POST_PUBLICACION = 'POST_PUBLICACION';
export const SHARE_PUBLICACION = 'SHARE_PUBLICACION'
// Eventos
export const SET_EVENTOS = 'SET_EVENTOS';
export const LIKE_EVENTO ='LIKE_EVENTO';
export const UNLIKE_EVENTO='UNLIKE_EVENTO';
export const DELETE_EVENTO='DELETE_EVENTO';
export const POST_EVENTO = 'POST_EVENTO';
// CHATS 
export const SET_USUARIOS ="SET_USUARIOS";
export const SET_CHAT="SET_CHAT";
export const SET_MENSAJES="SET_MENSAJES";
export const POST_MENSAJE="POST_MENSAJE";


export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

